# https://doc.rust-lang.org/cargo/reference/config.html

# NOTE: https://github.com/rust-lang/cargo/issues/3946#issuecomment-973132993
[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }

# https://doc.rust-lang.org/cargo/reference/profiles.html#dev
[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

# https://doc.rust-lang.org/cargo/reference/profiles.html#release
[profile.release]
overflow-checks = true
panic = "abort"

[profile.profiling]
inherits = "release"
debug = true
